###
# @Author       : jiaopengzi
# @BuildDate    : 2024-11-01 10:16:49
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 在这里定义全局变量
      KERNEL_VERSION: '6.6' # 可选内核版本 6.6 | 6.1 | 5.15 | 5.10 | 5.4
      CONFIG_FILE: 'x86_64.config' # 配置文件

    steps:
      - name: 9. 设置日期环境变量
        id: date
        run: |
          TZ='Asia/Shanghai'
          DATE=$(date "+%Y%m%d%H%M%S")
          echo "DATE=$DATE" >> $GITHUB_ENV
          touch ./date.txt

      - name: 10. 上传编译固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64-${{ env.DATE }}-${{ github.run_id }}
          path: ./date.txt
          retention-days: 3 # 设置保留天数为3天
      - name: 11. 停止job
        run: |
          echo "======================================== 停止job"
          exit 0
