###
# @Date         : 2024-02-16 11:03:16
# @Description  : 用于在 github actions 中编译 OpenWrt 固件
###

name: Build OpenWrt

on:
  workflow_dispatch:
    # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4

      - name: 2. 清理磁盘空间
        run: |
          sudo rm -rf \
            /usr/share/dotnet \
            /usr/local/lib/android \
            /opt/ghc \
            /etc/mysql \
            /etc/php
          sudo apt clean
          sudo rm -rf /var/lib/apt/lists/*
          df -h

      - name: 3. 运行 build-openwrt-online.sh 脚本
        run: |
          chmod +x build-openwrt-online.sh
          ./build-openwrt-online.sh

      - name: 4. 打包构建产物
        run: |
          zip -r openwrt_bin.zip ./openwrt/bin/targets/x86/64
        shell: bash

      - name: 5. 上传压缩包到 GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_bin
          path: openwrt_bin.zip
