###
# @Author       : jiaopengzi
# @BuildDate    : 2024-10-26 14:32:04
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 2. 缓存工具链
        uses: klever1988/cachewrtbuild@main
        with:
          #是否一并缓存.ccache目录，如果你启用了ccache。这是唯一的常用参数，其他三个用于除错，一般不需要调整
          ccache: true

          #是否缓存工具链目录
          toolchain: true

          #是否跳过工具链编译
          skip: true

          #清空缓存
          clean: false

      - name: 3. 使用 jlumbroso/free-disk-space 释放磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 4. 运行 build-openwrt-online.sh 脚本
        run: |
          chmod +x build-openwrt-online.sh
          ./build-openwrt-online.sh

      - name: 5. 上传编译固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64
          path: ./openwrt/bin/targets/x86/64
