###
# @Author       : jiaopengzi
# @BuildDate    : 2024-10-26 14:32:04
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4

      - name: 2. 运行 build-openwrt-online.sh 脚本
        run: |
          chmod +x build-openwrt-online.sh
          ./build-openwrt-online.sh

      - name: 3. 上传编译固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64
          path: ./openwrt/bin/targets/x86/64
