###
# @Author       : jiaopengzi
# @BuildDate    : 2025-02-13 19:15:19
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # 更改工作目录
        working-directory: /mnt
    env:
      # 在这里定义全局变量
      KERNEL_VERSION: "6.6" # 可选内核版本 6.6 | 6.1 | 5.15 | 5.10 | 5.4
      CONFIG_FILE: "x86_64.config" # 配置文件

    steps:
      - name: __磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
          # 设置日期环境变量
          echo "DATETIME=$(TZ='Asia/Shanghai' date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: 1. 检出仓库
        uses: actions/checkout@v4

      - name: 3. 下载源码
        run: |
          sudo chmod -R 777 /mnt

          # 下载源码
          echo "======================================== 下载源码"

          git clone --depth 1 https://github.com/coolsnowwolf/lede -b master openwrt
          cd openwrt || exit

      - name: 5. make_download
        run: |
          echo "======================================== 版本:$KERNEL_VERSION 当前下载目录"
          pwd

          # 拷贝配置文件
          cp $GITHUB_WORKSPACE/$CONFIG_FILE /mnt/openwrt/.config

          echo "======================================== 版本:$KERNEL_VERSION 查看.config配置文件"
          cat /mnt/openwrt/.config
