###
# @Author       : jiaopengzi
# @BuildDate    : 2024-10-27 09:04:34
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 在这里定义全局变量
      KERNEL_VERSION: '6.6' # 内核版本
      CONFIG_FILE: 'x86_64.config' # 配置文件

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 2. 使用 jlumbroso/free-disk-space 释放磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 3. 再次手动释放磁盘空间
        run: |
          echo "======================================== 查看当前磁盘空间 磁盘空间清理完成前"
          df -h

          # 删除不必要的软件包
          sudo apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* mysql* php* mongodb* moby* snapd* || true

          # 删除不必要的文件和目录
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /etc/mysql
          sudo rm -rf /etc/php
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/man
          sudo rm -rf /usr/share/doc
          sudo rm -rf /usr/share/locale
          sudo rm -rf /usr/share/zoneinfo
          sudo rm -rf /usr/share/info
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          sudo rm -rf /home/*/.cache/*
          sudo rm -rf /root/.cache
          sudo rm -rf /etc/apt/sources.list.d/*
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo apt -y autoremove --purge
          sudo apt-get autoclean
          sudo apt-get clean

          echo "======================================== 查看当前磁盘空间 磁盘空间清理完成后"
          df -h

      - name: 4. 安装环境依赖
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
              bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
              git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
              libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
              libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python3 \
              python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
              uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev \
              make clang llvm nano python3-pip aria2 \
              bc lm-sensors pciutils curl miniupnpd conntrack conntrackd jq liblzma-dev \
              libpcre2-dev libpam0g-dev libkmod-dev libtirpc-dev libaio-dev libcurl4-openssl-dev libtins-dev libyaml-cpp-dev libglib2.0-dev libgpiod-dev

          echo "======================================== 查看当前磁盘空间 安装依赖后"
          df -h
      - name: 5. 下载源码
        run: |
          # 下载源码
          echo "======================================== 下载源码"

          git clone --depth 1 https://github.com/coolsnowwolf/lede -b master openwrt
          cd openwrt || exit

          # 添加 ssrp 源
          echo "src-git ssrp https://github.com/fw876/helloworld.git" >>./feeds.conf.default

          # 更新软件包 & 安装依赖,出现 warning 信息不影响编译
          echo "======================================== 更新软件包"
          ./scripts/feeds update -a

          echo "======================================== 查看当前磁盘空间 下载源码后"
          df -h
      - name: 6. 安装编译依赖
        run: |
          echo "======================================== 安装依赖"
          cd openwrt || exit
          ./scripts/feeds install -a

          echo "======================================== 二次安装依赖,确保安装完整"
          ./scripts/feeds install -a

          echo "======================================== 查看当前磁盘空间 安装编译依赖后"
          df -h
      - name: 7. make_download
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config

          # 打印当前目录
          echo "======================================== 版本:$KERNEL_VERSION 当前下载目录"
          cd openwrt || exit
          pwd

          # 指定内核版本
          sed -i "s/^KERNEL_PATCHVER:=.*$/KERNEL_PATCHVER:=$KERNEL_VERSION/" target/linux/x86/Makefile
          sed -i "s/^KERNEL_TESTING_PATCHVER:=.*$/KERNEL_TESTING_PATCHVER:=$KERNEL_VERSION/" target/linux/x86/Makefile

          echo "======================================== 版本:$KERNEL_VERSION 修改指定内核完成."

          # defconfig
          echo "======================================== 版本:$KERNEL_VERSION make defconfig"
          make defconfig

          # 查看编译线程最大值
          echo "======================================== 版本:$KERNEL_VERSION 下载线程数量:$(nproc)"

          # 下载 dl 库
          echo "======================================== 版本:$KERNEL_VERSION 下载dl库"
          make download -j"$(nproc)"

          echo "======================================== 查看当前磁盘空间 make_download完成时"
          df -h

      - name: 8. 编译固件
        run: |
          # 编译固件 稳妥起见，建议使用单线程编译

          echo "======================================== 版本:$KERNEL_VERSION 当前编译目录"
          cd openwrt || exit
          pwd

          echo "======================================== 版本:$KERNEL_VERSION 开始编译固件"
          make -j"$(nproc)"
          # make V=s -j1

          echo "======================================== 版本:$KERNEL_VERSION 编译完成"

          # 返回上层目录
          echo "======================================== 当前目录"
          cd ..
          pwd

          echo "======================================== 查看当前磁盘空间 编译完成,清理临时文件前"
          df -h

          # 删除基础镜像
          rm -f ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-rootfs.img.gz

          # 删除 kernel 文件
          rm -f ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-kernel.bin

          # 删除 packages 文件夹
          rm -rf ./openwrt/bin/targets/x86/64/packages

          # 清理临时文件
          echo "======================================== 清理临时文件"
          make clean

          echo "======================================== 查看当前磁盘空间 编译完成,清理临时文件后"
          df -h

      - name: 9. 上传编译固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64
          path: ./openwrt/bin/targets/x86/64
