###
# @Author       : jiaopengzi
# @BuildDate    : 2024-10-27 09:04:34
# @FilePath     : \build-openwrt\.github\workflows\build.yaml
# @Description  : GitHub Actions 自动构建 OpenWrt
###

name: Build OpenWrt

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      # 当 main 分支下的 .github/workflows/build.yaml 文件发生变化时触发
      - .github/workflows/build.yaml

  workflow_dispatch:
    # 手动触发

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # 限制并发构建，防止同时构建多个
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 在这里定义全局变量
      KERNEL_VERSION: '6.6' # 内核版本
      CONFIG_FILE: 'x86_64.config' # 配置文件

    steps:
      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 1. 磁盘空间优化
        # 参考:https://github.com/dzikaros/ActionsBuildOpenWRT/blob/main/.github/workflows/build-x86_64_ipv4.yml
        uses: 'hugoalh/disk-space-optimizer-ghaction@v0.8.1'
        with:
          operate_sudo: 'True'
          general_include: '.+'
          general_exclude: |-
            ^GCC$
            ^G\+\+$
            Clang
            LLVM
          docker_include: '.+'
          docker_prune: 'True'
          docker_clean: 'True'
          apt_prune: 'True'
          apt_clean: 'True'
          homebrew_prune: 'True'
          homebrew_clean: 'True'
          npm_prune: 'True'
          npm_clean: 'True'
          os_swap: 'True'

      - name: 2. 磁盘空间释放
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      # - name: 2. 使用 jlumbroso/free-disk-space 释放磁盘空间
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false

      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true

      # - name: 3. 再次手动释放磁盘空间
      #   run: |
      #     echo "======================================== 查看当前磁盘空间 磁盘空间清理完成前"
      #     df -h

      #     # 删除不必要的软件包
      #     sudo apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* mysql* php* mongodb* moby* snapd* || true

      #     # 删除不必要的文件和目录
      #     sudo rm -rf /etc/mysql
      #     sudo rm -rf /etc/apt/sources.list.d/*
      #     sudo rm -rf /etc/php

      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf /opt/hostedtoolcache/CodeQL

      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/share/man
      #     sudo rm -rf /usr/share/doc
      #     sudo rm -rf /usr/share/locale
      #     sudo rm -rf /usr/share/zoneinfo
      #     sudo rm -rf /usr/share/info

      #     sudo rm -rf /tmp/*
      #     sudo rm -rf /var/tmp/*

      #     sudo rm -rf /home/*/.cache/*
      #     sudo rm -rf /root/.cache

      #     sudo apt -y autoremove --purge
      #     sudo apt-get autoclean
      #     sudo apt-get clean

      #     echo "======================================== 查看当前磁盘空间 磁盘空间清理完成后"
      #     df -h

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 3. 检出仓库
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 4. 安装环境依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
              bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
              git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
              libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
              libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python3 \
              python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
              uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev \
              make clang llvm nano python3-pip aria2 \
              bc lm-sensors pciutils curl miniupnpd conntrack conntrackd jq liblzma-dev \
              libpcre2-dev libpam0g-dev libkmod-dev libtirpc-dev libaio-dev libcurl4-openssl-dev libtins-dev libyaml-cpp-dev libglib2.0-dev libgpiod-dev

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 5. 下载源码
        run: |
          # 下载源码
          echo "======================================== 下载源码"

          git clone --depth 1 https://github.com/coolsnowwolf/lede -b master openwrt
          cd openwrt || exit

          # 添加 ssrp 源
          echo "src-git ssrp https://github.com/fw876/helloworld.git" >>./feeds.conf.default

          # 更新软件包 & 安装依赖,出现 warning 信息不影响编译
          echo "======================================== 更新软件包"
          ./scripts/feeds update -a

      - name: 6. 缓存编译工具链
        # 参考：https://github.com/coolsnowwolf/lede/pull/7796
        uses: klever1988/cachewrtbuild@main
        with:
          #是否一并缓存.ccache目录，如果你启用了ccache。这是唯一的常用参数，其他三个用于除错，一般不需要调整
          ccache: true

          #是否缓存工具链目录
          toolchain: true

          #是否跳过工具链编译
          skip: true

          #清空缓存
          clean: false
          prefix: ${{ github.workspace }}/openwrt

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 7. 安装编译依赖
        run: |
          echo "======================================== 安装依赖"
          cd openwrt || exit
          ./scripts/feeds install -a

          echo "======================================== 二次安装依赖,确保安装完整"
          ./scripts/feeds install -a

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 8. make_download
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config

          # 打印当前目录
          echo "======================================== 版本:$KERNEL_VERSION 当前下载目录"
          cd openwrt || exit
          pwd

          # 指定内核版本
          sed -i "s/^KERNEL_PATCHVER:=.*$/KERNEL_PATCHVER:=$KERNEL_VERSION/" target/linux/x86/Makefile
          sed -i "s/^KERNEL_TESTING_PATCHVER:=.*$/KERNEL_TESTING_PATCHVER:=$KERNEL_VERSION/" target/linux/x86/Makefile

          echo "======================================== 版本:$KERNEL_VERSION 修改指定内核完成."

          # defconfig
          echo "======================================== 版本:$KERNEL_VERSION make defconfig"
          make defconfig

          # 查看编译线程最大值
          echo "======================================== 版本:$KERNEL_VERSION 下载线程数量:$(nproc)"

          # 下载 dl 库
          echo "======================================== 版本:$KERNEL_VERSION 下载dl库"
          make download -j"$(nproc)"

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 9. 清理编译目录
        run: |
          echo "======================================== 版本:$KERNEL_VERSION 当前编译目录"
          cd openwrt || exit
          pwd
          make clean

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 10. 编译固件
        run: |
          echo "======================================== 版本:$KERNEL_VERSION 当前编译目录"
          cd openwrt || exit
          pwd

          echo "======================================== 版本:$KERNEL_VERSION 开始编译固件"
          make -j"$(nproc)"
          # make V=s -j1

          echo "======================================== 版本:$KERNEL_VERSION 编译完成"

          # 返回上层目录
          echo "======================================== 当前目录"
          cd ..
          pwd


          # 删除基础镜像
          rm -f ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-rootfs.img.gz

          # 删除 kernel 文件
          rm -f ./openwrt/bin/targets/x86/64/openwrt-x86-64-generic-kernel.bin

          # 删除 packages 文件夹
          rm -rf ./openwrt/bin/targets/x86/64/packages

          # 清理临时文件
          echo "======================================== 清理临时文件"
          make clean

      - name: 磁盘空间监控
        run: |
          echo "磁盘空间监控"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 11. 上传编译固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64
          path: ./openwrt/bin/targets/x86/64
